<?xml version="1.0" encoding="utf-8"?><Database Name="jiajuksnewstest20150410-1209" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=jiajuksnewstest20150410-1209;Persist Security Info=True;User ID=sa" SettingsObjectName="Haojibiz.Properties.Settings" SettingsPropertyName="jiajuksnewstest20150410_1209ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ShoppingAddress" Member="ShoppingAddress">
    <Type Name="ShoppingAddress">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Consignee" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ProvinceName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ProvinceCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CityCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="AreaName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="AreaCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_BiYing" Member="T_BiYing">
    <Type Name="T_BiYing">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Msg" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImgPath" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contact_time" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Pavilion" Member="t_Pavilion">
    <Type Name="t_Pavilion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Mid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MarketId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Bannel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="thumb" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderList" Member="OrderList">
    <Type Name="OrderList">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderNumber" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CustomerUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Consignee" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Freight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="InstallationFee" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TransportMeth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoiceClaim" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InvoiceTop" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="InvoiceAddress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="InvoiceZipcode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PayCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentCount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PaymentMinCount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PayType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Result" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivitieType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="out_trade_no" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Deliverystatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderDel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="trade_no" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="gmt_create" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="gmt_payment" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="buyer_email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="buyer_id" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="total_fee" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="body" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="extra_common_param" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupBuy" Member="GroupBuy">
    <Type Name="GroupBuy">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="brandId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="brandName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="brandImgUrl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ImgUrl" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="DiscountPerson1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountResult1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiscountPerson2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountResult2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Unline" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ShowPosition" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Orderby" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isdefault" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiscountUser1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountUser2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountBegin" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderInfor" Member="OrderInfor">
    <Type Name="OrderInfor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="productattributeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderNumber" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="BuyCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PayPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Deliverystatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Company_pay" Member="Company_pay">
    <Type Name="Company_pay">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViPType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyYearLen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="trade_no" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="gmt_create" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="gmt_payment" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="buyer_email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="buyer_id" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="total_fee" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="body" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="extra_common_param" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_member" Member="t_member">
    <Type Name="t_member">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="paypassword" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="passport" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="groupid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sound" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="tname" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="msn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="qq" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="skype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ali" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="areacode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="department" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="career" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="sms" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="integral" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="money" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="bank" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="alipay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="regip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="regtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="loginip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="logintime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="logincount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="auth" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="authvalue" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="authtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="vemail" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vmobile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vname" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vbank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vcompany" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="valipay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="support" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="inviter" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="lastedittime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="chat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="message" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="question" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="answer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="overprice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="useprice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Isrecharge" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RegStatcTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegEndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lookTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="vipLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parentid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="shopid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderListMemberRead" Member="OrderListMemberRead">
    <Type Name="OrderListMemberRead">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_marketstoreyshop" Member="t_marketstoreyshop">
    <Type Name="t_marketstoreyshop">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="marketid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="markettitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="storeyid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="storeytitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="shopid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="shoptitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="brandidlist" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="brandtitlelist" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="istop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isrecommend" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lev" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedittime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="position" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="source" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="linestatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PavilionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_dealer" Member="t_dealer">
    <Type Name="t_dealer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="letter" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="groupid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attribute" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="industry" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="productcategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="vip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areacode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="mapapi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="staffsize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="regyear" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="regcity" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="buy" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="sell" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="linkman" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mphone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="postcode" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="homepage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="domain" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="domainip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="icp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="surface" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="thumb" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="bannel" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="desimage" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="descript" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="keywords" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="template" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createmid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedittime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="auditstatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="linestatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dbook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Createtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sortstr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsPay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="dealertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_brand" Member="t_brand">
    <Type Name="t_brand">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="companyid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="letter" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="groupid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="attribute" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="productcategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="homepage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="productcount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="spread" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="material" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="style" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="surface" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="thumb" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="bannel" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="desimage" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="descript" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="keywords" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="template" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createmid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lasteditid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedittime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="auditstatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="linestatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Createtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sortstr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsPay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Recommend" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecommendSort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowNav" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_shop" Member="t_shop">
    <Type Name="t_shop">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="letter" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="groupid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attribute" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="industry" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="productcategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="vip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areacode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="mapapi" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="staffsize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="regyear" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="regcity" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="buy" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="sell" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="linkman" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mphone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="postcode" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="homepage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="domain" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="domainip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="icp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="surface" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="thumb" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="bannel" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="desimage" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="descript" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="keywords" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="template" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="marketid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ctype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createmid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedittime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="auditstatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="linestatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="qq" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="sortstr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsPay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SecondClerk" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ShopContact" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FirstClerkMobile" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SecondClerkMobile" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="isshopshare" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PavilionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_product" Member="t_product">
    <Type Name="t_product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="attribute" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="shottitle" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="tcolor" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="sku" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="no" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="letter" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="categoryid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="categorytitle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="subcategoryidlist" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="subcategorytitlelist" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="brandid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="brandtitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="brandsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="brandstitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="stylevalue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="stylename" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="colorname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="colorvalue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="materialvalue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="materialname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="localitycode" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="shipcode" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="customize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="surface" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="thumb" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="bannel" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="desimage" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="descript" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="tob2c" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="companyid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="companyname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="createmid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedittime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="auditstatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="linestatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="assemble" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Createtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sortstr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsPay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="shopid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="homepageimg" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_company" Member="t_company">
    <Type Name="t_company">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="letter" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="groupid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attribute" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="industry" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="productcategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="vip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="areacode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="mapapi" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="staffsize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="regyear" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="regcity" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="buy" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="sell" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="linkman" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mphone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="postcode" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="homepage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="domain" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="domainip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="icp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="surface" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="thumb" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="bannel" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="desimage" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="descript" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="keywords" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="template" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createmid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastedittime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="auditstatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="linestatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="license" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="registration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="organization" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Createtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sortstr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsPay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="QQWeiBo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Duty" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cPerson" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ContactType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="brandInfo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IpAddress" Member="IpAddress">
    <Type Name="IpAddress">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ip" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>